# Generated by Django 3.2 on 2023-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registration_limit',
            field=models.CharField(max_length=2000, verbose_name='محدودیت اخذ'),
        ),
    ]
