# Generated by Django 3.2 on 2023-06-20 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecourse',
            name='course_studying_gp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.coursestudyinggp', verbose_name='دوره آموزشی درس'),
        ),
        migrations.AlterField(
            model_name='basecourse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_courses', to='university.department', verbose_name='دانشکده درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='base_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university.basecourse', verbose_name='درس پایه'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university.semester', verbose_name='ترم ارائه'),
        ),
    ]
