# Generated by Django 3.2 on 2023-06-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230620_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WalletTransactions',
            new_name='WalletTransaction',
        ),
    ]
