# Generated by Django 3.2 on 2023-06-20 07:16

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_wallettransactions_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='applied_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
