# Generated by Django 3.2 on 2023-07-04 05:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_count_of_verification_code_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('telegram_id', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='telegram id must be alphanumeric or contain underscores', regex='^[a-zA-Z0-9_]+$'), django.core.validators.MinLengthValidator(5, message='telegram id must be at least 5 characters long.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
