# Generated by Django 3.2 on 2023-07-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_registration_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_registration_tries_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_registration_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_verification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
