# Generated by Django 3.2 on 2023-07-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230704_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_registration_tries_reset',
            new_name='has_verification_tries_reset',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='count_of_verification_code_sent',
            new_name='verification_tries_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_registration_sent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_tries',
        ),
    ]
