version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
       DB_URL: postgres://postgres:postgres@db:5432/postgres


  db:
    image: postgres
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend


volumes:
  postgres_data:
  static_volume:
  media_volume:


