# Generated by Django 3.2 on 2023-12-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='time_created',
            new_name='created_at',
        ),
    ]
