# Generated by Django 3.2 on 2023-12-15 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0005_twitte_display'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user2',
        ),
        migrations.AddField(
            model_name='room',
            name='profile1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile1_rooms', to='social_media.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='profile2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile2_rooms', to='social_media.profile'),
            preserve_default=False,
        ),
    ]
