# Generated by Django 3.2 on 2023-04-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('CE', 'Computer Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('IE', 'Industrial Engineering'), ('CHE', 'Chemical Engineering'), ('MATE', 'Material Engineering'), ('RE', 'Railway Engineering'), ('CS', 'Computer Science')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
