# Generated by Django 3.2 on 2023-06-20 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=20000, max_digits=10),
        ),
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('D', 'کاهش'), ('C', 'افزایش')], max_length=1, verbose_name='نوع تراکنش')),
                ('transaction_status', models.CharField(choices=[('P', 'در حال پردازش'), ('C', 'موفق'), ('F', 'ناموفق')], max_length=1, verbose_name='وضعیت تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش های کیف پول',
                'ordering': ['-applied_at'],
            },
        ),
    ]
