# Generated by Django 3.2 on 2023-06-20 08:54

from django.db import migrations, models
import utils.transactions.transaction_functions


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='ref_code',
            field=models.CharField(default=utils.transactions.transaction_functions.create_ref_code, max_length=20, verbose_name='کد مرجع'),
        ),
    ]
