# Generated by Django 3.2 on 2023-07-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_wallettransaction_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_of_verification_code_sent',
            field=models.IntegerField(default=0),
        ),
    ]
