# Generated by Django 3.2 on 2023-07-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230704_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_tries',
            field=models.IntegerField(default=0),
        ),
    ]
