# Generated by Django 3.2 on 2023-11-02 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'max_length': 'نام کاربری باید حداکثر ۲۰ کاراکتر باشد', 'min_length': 'نام کاربری باید حداقل ۶ کاراکتر باشد', 'unique': 'نام کاربری تکراری است'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
