# Generated by Django 3.2 on 2023-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0004_auto_20230522_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltracker',
            name='action',
            field=models.CharField(choices=[('C', 'ایجاد'), ('U', 'بروزرسانی'), ('D', 'حذف')], max_length=1, verbose_name='عملیات'),
        ),
    ]
