# Generated by Django 3.2 on 2023-06-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0005_alter_modeltracker_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltracker',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام درس'),
        ),
        migrations.AddField(
            model_name='modeltracker',
            name='course_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره درس'),
        ),
        migrations.AddField(
            model_name='modeltracker',
            name='is_course',
            field=models.BooleanField(blank=True, default=False, verbose_name='درس است؟'),
        ),
    ]
