# Generated by Django 3.2 on 2023-06-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0009_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('O', 'پرداخت آنلاین'), ('W', 'پرداخت از طریق کیف پول')], default='O', max_length=1),
        ),
    ]
