# Generated by Django 3.2 on 2023-07-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0017_auto_20230707_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackers', to='custom_config.modeltracker'),
        ),
    ]
