# Generated by Django 3.2 on 2023-07-06 21:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_config', '0018_notification_tracker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='WebNotification',
        ),
    ]
