# Generated by Django 3.2 on 2023-07-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0020_webnotification_custom_conf_user_id_0f652c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltracker',
            name='status',
            field=models.CharField(choices=[('U', 'اعمال نشده'), ('C', 'اعمال شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
