# Generated by Django 3.2 on 2023-11-02 21:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, error_messages={'max_length': 'نام باید حداکثر ۵۰ کاراکتر باشد'}, max_length=50, null=True)),
                ('username', models.CharField(blank=True, error_messages={'max_length': 'نام کاربری باید حداکثر ۲۰ کاراکتر باشد', 'min_length': 'نام کاربری باید حداقل ۶ کاراکتر باشد', 'unique': 'نام کاربری تکراری است'}, max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('image', models.ImageField(default='images/profile_pics/default.png', upload_to='images/profile_pics')),
                ('profile_type', models.CharField(choices=[('T', 'استاد'), ('C', 'درس'), ('U', 'کاربر'), ('V', 'کاربر تاییدشده')], default='U', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='social_media.profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='social_media.profile')),
            ],
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['content_type', 'object_id'], name='social_medi_content_823d82_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['username'], name='social_medi_usernam_80b3bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'following'], name='social_medi_followe_5fb8d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
