# Generated by Django 3.2 on 2023-10-28 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social_media', '0002_auto_20231028_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['content_type', 'object_id'], name='social_medi_content_823d82_idx'),
        ),
    ]
