# Generated by Django 3.2 on 2023-11-30 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTwitte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('S', 'اسپم'), ('P', 'پورن'), ('V', 'خشونت'), ('O', 'سایر')], max_length=1)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_twittes', to='social_media.profile')),
                ('twitte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='social_media.twitte')),
            ],
        ),
        migrations.AddIndex(
            model_name='reporttwitte',
            index=models.Index(fields=['reporter', 'twitte'], name='social_medi_reporte_b57d1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reporttwitte',
            unique_together={('reporter', 'twitte')},
        ),
    ]
