# Generated by Django 3.2 on 2023-11-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_auto_20231130_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitte',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
