# Generated by Django 3.2 on 2023-11-02 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0007_auto_20231102_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, error_messages={'max_length': 'نام باید حداکثر ۵۰ کاراکتر باشد'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, error_messages={'max_length': 'نام کاربری باید حداکثر ۲۰ کاراکتر باشد', 'min_length': 'نام کاربری باید حداقل ۶ کاراکتر باشد', 'unique': 'نام کاربری تکراری است'}, max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['username'], name='social_medi_usernam_80b3bd_idx'),
        ),
    ]
