# Generated by Django 3.2 on 2023-05-12 17:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='مدل')),
                ('instance_id', models.IntegerField(verbose_name='شناسه')),
                ('action', models.CharField(choices=[('C', 'ایجاد'), ('U', 'بروزرسانی')], max_length=1, verbose_name='عملیات')),
                ('status', models.CharField(choices=[('U', 'اعمال نشده'), ('C', 'اعمال شده')], max_length=1, verbose_name='وضعیت')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'ترکر',
                'verbose_name_plural': 'ترکرها',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255, verbose_name='ستون')),
                ('value', models.CharField(max_length=1023, verbose_name='مقدار')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='custom_config.modeltracker', verbose_name='ترکر')),
            ],
            options={
                'verbose_name': 'تغییرات ستون',
                'verbose_name_plural': 'تغییر ستون ها',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contain_telegram', models.BooleanField(default=False)),
                ('contain_sms', models.BooleanField(default=False)),
                ('contain_email', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='custom_config.cart')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course')),
            ],
            options={
                'unique_together': {('cart', 'course')},
            },
        ),
    ]
