# Generated by Django 3.2 on 2023-05-14 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0002_course_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='ModelTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='مدل')),
                ('instance_id', models.IntegerField(verbose_name='شناسه')),
                ('action', models.CharField(choices=[('C', 'ایجاد'), ('U', 'بروزرسانی')], max_length=1, verbose_name='عملیات')),
                ('status', models.CharField(choices=[('U', 'اعمال نشده'), ('C', 'اعمال شده')], max_length=1, verbose_name='وضعیت')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'ترکر',
                'verbose_name_plural': 'ترکرها',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('P', 'در حال پردازش'), ('C', 'موفق'), ('F', 'ناموفق')], default='P', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'آیتم های سفارش',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contain_telegram', models.BooleanField(default=False)),
                ('contain_sms', models.BooleanField(default=False)),
                ('contain_email', models.BooleanField(default=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='university.course')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='custom_config.order')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'آیتم های سفارش',
            },
        ),
        migrations.CreateModel(
            name='FieldTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255, verbose_name='ستون')),
                ('value', models.CharField(max_length=1023, verbose_name='مقدار')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='custom_config.modeltracker', verbose_name='ترکر')),
            ],
            options={
                'verbose_name': 'تغییرات ستون',
                'verbose_name_plural': 'تغییر ستون ها',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contain_telegram', models.BooleanField(default=False)),
                ('contain_sms', models.BooleanField(default=False)),
                ('contain_email', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='custom_config.cart')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='university.course')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم های سبد خرید',
                'unique_together': {('cart', 'course')},
            },
        ),
    ]
