# Generated by Django 3.2 on 2023-05-22 06:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_course_semester'),
        ('custom_config', '0002_reviewvote_teacherreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherreview',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_review', to='university.teacher'),
        ),
        migrations.AlterField(
            model_name='teacherreview',
            name='vote',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
