# Generated by Django 3.2 on 2023-06-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0006_auto_20230604_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='course_code',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
