# Generated by Django 3.2 on 2023-06-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0007_orderitem_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='course_code',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='class_gp',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='course_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['course_number', 'class_gp'], name='custom_conf_course__59ee07_idx'),
        ),
    ]
