# Generated by Django 3.2 on 2023-06-20 08:54

from django.db import migrations, models
import django.db.models.deletion
import utils.transactions.transaction_functions


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0010_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('success', models.BooleanField(default=False)),
                ('ref_code', models.CharField(default=utils.transactions.transaction_functions.create_ref_code, max_length=20, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='custom_config.order')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
