# Generated by Django 3.2 on 2023-07-06 20:50

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0015_alter_order_placed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltracker',
            name='status',
            field=models.CharField(choices=[('U', 'اعمال نشده'), ('T', 'اعمال شده')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent_to_telegram', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('applied_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('order_items', models.ManyToManyField(related_name='notifications', to='custom_config.OrderItem')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
            },
        ),
    ]
