# Generated by Django 3.2 on 2023-07-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0019_rename_notification_webnotification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webnotification',
            index=models.Index(fields=['user', 'is_read'], name='custom_conf_user_id_0f652c_idx'),
        ),
    ]
