# Generated by Django 3.2 on 2023-11-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0021_alter_modeltracker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webnotification',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
