# Generated by Django 3.2 on 2023-11-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0023_auto_20231124_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
