# Generated by Django 3.2 on 2023-11-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_config', '0024_cart_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='submitted',
        ),
    ]
