# Generated by Django 3.2 on 2023-05-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_user_telegram_telegram_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_telegram',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='user_telegram',
            name='telegram_first_name',
        ),
        migrations.RemoveField(
            model_name='user_telegram',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='user_telegram',
            name='telegram_last_name',
        ),
        migrations.AddField(
            model_name='user_telegram',
            name='hashed_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_telegram',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
