# Generated by Django 3.2 on 2023-05-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_auto_20230520_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_telegram',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
