# Generated by Django 3.2 on 2023-03-29 08:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCourse',
            fields=[
                ('course_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='شماره درس')),
                ('name', models.CharField(max_length=255, verbose_name='نام درس')),
                ('total_unit', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='کل واحد')),
                ('practical_unit', models.PositiveSmallIntegerField(verbose_name='واحد های عملی')),
                ('emergency_deletion', models.BooleanField(verbose_name='حذف اضطراری')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_gp', models.CharField(max_length=2, verbose_name='گروه درس')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='ظرفیت')),
                ('registered_count', models.PositiveSmallIntegerField(verbose_name='تعداد ثبت نام شده ها')),
                ('waiting_count', models.PositiveSmallIntegerField(verbose_name='تعداد افراد حاضر در لیست انتظار')),
                ('sex', models.CharField(choices=[('C', 'Male'), ('F', 'Female'), ('B', 'Both')], max_length=1, verbose_name='جنسیت')),
                ('guest_able', models.BooleanField(verbose_name='قابل اخذ توسط مهمان')),
                ('description', models.CharField(max_length=511, verbose_name='توضیحات')),
                ('presentation_type', models.CharField(choices=[('N', 'Normal'), ('E', 'Electronic'), ('B', 'Both')], max_length=1, verbose_name='نحوه ارائه درس')),
                ('base_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.basecourse', verbose_name='درس پایه')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudyingGP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_id', models.IntegerField(verbose_name='کد دوره آموزشی')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام دوره آموزشی')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_number', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='کد دانشکده')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام دانشکده')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False, verbose_name='ترم ارائه درس')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTimePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ امتحان')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('place', models.CharField(max_length=255, verbose_name='مکان امتحان')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course', verbose_name='درس')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTimePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('day', models.IntegerField(choices=[(1, 'شنبه'), (2, 'یکشنبه'), (3, 'دو شنبه'), (4, 'سه شنبه'), (5, 'چهار شنبه'), (6, 'پنجشنبه'), (7, 'جمعه')], verbose_name='روز جلسه')),
                ('place', models.CharField(max_length=255, verbose_name='مکان برگزاری جلسه')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course', verbose_name='درس')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.teacher', verbose_name='استاد درس'),
        ),
        migrations.AddField(
            model_name='basecourse',
            name='course_studying_gp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.coursestudyinggp', verbose_name='دوره آموزشی درس'),
        ),
        migrations.AddField(
            model_name='basecourse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.department', verbose_name='دانشکده درس'),
        ),
        migrations.AddField(
            model_name='basecourse',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.semester', verbose_name='ترم ارائه'),
        ),
    ]
