# Generated by Django 3.2 on 2023-03-29 07:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('total_unit', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('practical_unit', models.PositiveSmallIntegerField()),
                ('emergency_deletion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_gp', models.CharField(max_length=2)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('registered_count', models.PositiveSmallIntegerField()),
                ('waiting_count', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('C', 'Male'), ('F', 'Female'), ('B', 'Both')], max_length=1)),
                ('guest_able', models.BooleanField()),
                ('description', models.CharField(max_length=511)),
                ('presentation_type', models.CharField(choices=[('N', 'Normal'), ('E', 'Electronic'), ('B', 'Both')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.basecourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudyingGP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_id', models.IntegerField()),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTimePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTimePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.IntegerField(choices=[(1, 'شنبه'), (2, 'یکشنبه'), (3, 'دو شنبه'), (4, 'سه شنبه'), (5, 'چهار شنبه'), (6, 'پنجشنبه'), (7, 'جمعه')])),
                ('place', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course')),
            ],
        ),
        migrations.AddField(
            model_name='basecourse',
            name='course_studying_gp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.coursestudyinggp'),
        ),
        migrations.AddField(
            model_name='basecourse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.department'),
        ),
        migrations.AddField(
            model_name='basecourse',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.semester'),
        ),
    ]
