# Generated by Django 3.2 on 2023-04-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_number',
            field=models.SmallIntegerField(default=1, primary_key=True, serialize=False, verbose_name='کد دانشکده'),
        ),
    ]
