<<<<<<< HEAD
# Generated by Django 3.2 on 2023-05-09 18:22
=======
# Generated by Django 3.2 on 2023-05-07 17:21
>>>>>>> 346843de0fda96f50f2e78d239d61d256caf76a8

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
