# Generated by Django 3.2 on 2023-04-13 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetimeplace',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_times', to='university.course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='examtimeplace',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_times', to='university.course', verbose_name='درس'),
        ),
    ]
