<<<<<<< HEAD
# Generated by Django 3.2 on 2023-05-12 17:36
=======
# Generated by Django 3.2 on 2023-05-09 18:22
>>>>>>> ada8105eb361286bdfe629bc7dad9bd6ac543280

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
