# Generated by Django 3.2 on 2023-03-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20230329_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
