# Generated by Django 3.2 on 2023-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_department_department_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_number',
            field=models.SmallIntegerField(default=2, primary_key=True, serialize=False, verbose_name='کد دانشکده'),
        ),
    ]
