# Generated by Django 3.2 on 2023-05-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_course_registration_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='golestan_name',
            field=models.CharField(db_index=True, default='teacher', max_length=255, unique=True, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_lms_image',
            field=models.ImageField(blank=True, default='images/teachers_image/default.png', upload_to='images/teachers_image/', verbose_name='تصویر استاد'),
        ),
    ]
