# Generated by Django 3.2 on 2023-03-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetimeplace',
            name='day',
            field=models.IntegerField(choices=[(1, 'شنبه'), (2, 'یک شنبه'), (3, 'دوشنبه'), (4, 'سه شنبه'), (5, 'چهارشنبه')], verbose_name='روز جلسه'),
        ),
    ]
