# Generated by Django 3.2 on 2023-04-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecourse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_courses', to='university.department', verbose_name='دانشکده درس'),
        ),
        migrations.AlterField(
            model_name='basecourse',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_courses', to='university.semester', verbose_name='ترم ارائه'),
        ),
        migrations.AlterField(
            model_name='course',
            name='base_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='university.basecourse', verbose_name='درس پایه'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='university.teacher', verbose_name='استاد درس'),
        ),
    ]
