# Generated by Django 3.2 on 2023-04-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20230414_0059'),
        ('university', '0005_alter_department_department_number'),
    ]

    operations = [
    ]
