# Generated by Django 3.2 on 2023-04-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20230422_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_departments', to='university.course', verbose_name='درس')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_departments', to='university.department', verbose_name='دانشکده')),
            ],
            options={
                'verbose_name': 'دانشکدۀ مجاز و غیر مجاز',
                'verbose_name_plural': 'دانشکده های مجاز و غیر مجاز',
            },
        ),
    ]
