# Generated by Django 3.2 on 2023-10-19 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20230621_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecourse',
            name='course_number',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Must be an 7-digit number')], verbose_name='شماره درس'),
        ),
    ]
