# Generated by Django 3.2 on 2023-11-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_alter_basecourse_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecourse',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='golestan_name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
