# Generated by Django 3.2 on 2023-04-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_alloweddepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=4, verbose_name='کد رنگ')),
                ('percantage_of_black', models.PositiveSmallIntegerField(verbose_name='درصد سیاهی')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_departments', to='university.department', verbose_name='دانشکده')),
            ],
        ),
    ]
