# Generated by Django 3.2 on 2023-11-02 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_auto_20231103_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registered_count',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد ثبت نام شده ها'),
        ),
        migrations.AlterField(
            model_name='course',
            name='waiting_count',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد افراد حاضر در لیست انتظار'),
        ),
    ]
