# Generated by Django 3.2 on 2023-11-03 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_auto_20231103_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecourse',
            name='course_number',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(9999999)], verbose_name='شماره درس'),
        ),
        migrations.AlterField(
            model_name='coursestudyinggp',
            name='gp_id',
            field=models.PositiveSmallIntegerField(verbose_name='کد گروه آموزشی'),
        ),
        migrations.AlterField(
            model_name='coursestudyinggp',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام گروه آموزشی'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد دانشکده'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام دانشکده'),
        ),
    ]
