# Generated by Django 3.2 on 2023-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_auto_20231103_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='lms_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره استاد در سامانه LMS'),
        ),
    ]
