# Generated by Django 3.2 on 2023-11-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_alter_teacher_lms_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtimeplace',
            name='date',
            field=models.DateField(help_text='سال را به فرم yyyy-mm-dd وارد کنید.', verbose_name='تاریخ امتحان'),
        ),
    ]
