# Generated by Django 3.2 on 2023-11-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_alter_teacher_lms_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('class_gp', 'base_course')},
        ),
    ]
