name: Django CI/CD  
on:  
  push:  
    branches: [ main ] 

jobs:  
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2

      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

      
    - name: Build the Docker image
      run: docker-compose -f docker-compose.yml build
      
    - name: Build  Docker image
      run: | 
        chmod +x ./start.sh
        chmod +x ./deployment/start_app.sh
        chmod +x ./deployment/start_daphne.sh


    - name: Run tests  
      run: pytest

  Deploy:  
    needs: build-and-test  
    name: deploy  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2  
      - name: Print masked secrets  
        run: |  
          echo "USERNAME: ${{ secrets.USERNAME }}"  
          echo "PASSWORD: ${{ secrets.PASSWORD }}"  
          echo "HOST: ${{ secrets.HOST }}"  
          echo "PORT: ${{ secrets.PORT }}"  
          echo "PATH: ${{ secrets.PATH }}"
      - uses: actions/checkout@v2  
      - name: Connect  
        uses: appleboy/ssh-action@master  
        with:  
          username: ${{ secrets.USERNAME }}  
          password: ${{ secrets.PASSWORD }}  
          host: ${{ secrets.HOST }}  
          port: ${{ secrets.PORT }}  
          script: |  
            cd ${{ secrets.PATH }}  
            docker compose stop  
            git pull  
            docker compose restart
