name: Django CI/CD  
on:  
  push:  
    branches: [ main ] 


jobs:  
  build-and-test :
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test

  deploy:  
    needs: build-and-test  
    runs-on: ubuntu-latest  
    if: github.ref == 'refs/heads/master'  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v2  

    - name: Setup SSH  
      uses: webfactory/ssh-agent@v0.5.0  
      with:  
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  

    - name: Deploy to VPS  
      run: |  
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} -p ${{ secrets.VPS_PORT }} <<EOF  
          cd /path/to/your/project  
          docker-compose -f docker-compose.yml down  
          git pull  
          docker-compose -f docker-compose.yml up --build -d  
        EOF
