# Generated by Django 3.2 on 2023-05-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(max_length=10, unique=True, verbose_name='شناسه تلگرام')),
                ('user_id', models.CharField(max_length=10, unique=True, verbose_name='شناسه کاربر')),
                ('telegram_id', models.CharField(max_length=255, unique=True, verbose_name='شناسه تلگرام')),
                ('telegram_first_name', models.CharField(max_length=255, verbose_name='نام')),
            ],
        ),
    ]
