# Generated by Django 3.2 on 2023-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_user_telegram_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_telegram',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
