# Generated by Django 3.2 on 2023-06-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_alter_user_telegram_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_telegram',
            name='telegram_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
